### ISSUE TITLE
checkInternetConnectivity Falsely Claiming Phone Is Not Connected to Internet When Switching from Wifi to Mobile Data Only

### ISSUE THREAD

**Issue by vedantroy** [pwittchen/ReactiveNetwork#276]
Preface - I'm very new to RxJava, so this may be my mistake. 

I have the following code that is taken directly from the readme, albeit I added in some logging statements.

```
ReactiveNetwork
                .observeNetworkConnectivity(context)
                .flatMapSingle(connectivity -> {
                    if (connectivity.getState() == NetworkInfo.State.CONNECTED) {
                        return ReactiveNetwork.checkInternetConnectivity();
                    }
                    Log.d(tag,"Not connected to network");
                    return Single.fromCallable(() -> false);
                })
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(isConnected -> {
                    if(isConnected) {
                        Log.d(tag,"Connected to network & internet");
                    } else {
                        Log.d(tag,"Connected to network but not internet");
                    }
                });
```

I've noticed something odd. If I'm connected to both wifi and cellular data and then I disconnect from the wifi, but I am still on cellular data, I will get the following output immediately after I disconnect from the wifi:

> Not connected to network
> Connected to network but not internet

My phone is a real Moto Gen 3.

The relevant files are attached. The Main Activity class is in Kotlin and the actual code for checking for network/internet connectivity is in a separate Java class because I couldn't figure out how to convert the above Java code to Kotlin.

[test.zip](https://github.com/pwittchen/ReactiveNetwork/files/2087030/test.zip)

Also, here is my build.gradle file:

[build.zip](https://github.com/pwittchen/ReactiveNetwork/files/2087033/build.zip)

I'm pretty sure the problem is not with my phone because after disconnecting from the wifi (but still remaining on cellular data) if I refresh the activity (press home button and then click app icon again), then logcat will output "Connected to network & internet"

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting this issue. I need to verify that. It looks like issue similar to #170.

Regards,
Piotr

**Comment by vedantroy** [comment]
@pwittchen Is there any potential work around for this issue until it gets fixed? 

I've thought of two work arounds:

1]

Considering logcat gives the proper output after I refresh my app, I think the issue might go away if I call  checkInternetConnectivity twice (with a small delay in between each time) after the phone connects to a network instead of calling it just once. But, I'm not sure how to implement that in the above code. 

2] I could also use observeInternetConnectivity, but I'm worried that will harm battery life/increase data consumption.

**Comment by pwittchen** [comment]
I need to investigate it, to be sure what kind of solution can be applied here or if it can be solved inside the library. 

`observeInternetConnectivity` should solve this. Nevertheless, it could increase battery usage and data consumption. You can customize delay and set it to a higher value, to reduce battery drain.

**Comment by pwittchen** [comment]
I used the same sample from `README.md`.

```java
...

  @Override protected void onResume() {
    super.onResume();

    networkDisposable = ReactiveNetwork.observeNetworkConnectivity(getApplicationContext())
        .flatMapSingle(connectivity -> {
          if (connectivity.getState() == NetworkInfo.State.CONNECTED) {
            return ReactiveNetwork.checkInternetConnectivity();
          }
          return Single.fromCallable(() -> false);
        })
        .subscribeOn(Schedulers.io())
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(isConnected -> {
          tvConnectivityStatus.setText(String.format("%s", isConnected.toString()));
        });
}

...
```

Here are results of my investigation:

assumption: both WiFi and mobile network have an Internet access

**scenario 1**

1. Connect to WiFi
2. Connect to the mobile network
3. Disconnect from WiFi
4. Status: connected

**scenario 2**

1. Connect to WiFi
2. Connect to the mobile network
3. Disconnect from mobile network
4. Status: connected

**scenario 3**

1. Connect to the mobile network
2. Connect to WiFi
3. Disconnect from mobile network
4. Status: connected

**scenario 4**

1. Connect to the mobile network
2. Connect to WiFi
3. Disconnect from WiFi
4. Status: **not connected**

so **scenario 4** is our edge case, which returns false positive values. I'll take a closer look on this. Of course, any kind of help is appreciated.

**Comment by pwittchen** [comment]
Ok,

I've done a few more investigations. It seems that following approach should solve this problem:

```java
    networkDisposable = ReactiveNetwork.observeNetworkConnectivity(getApplicationContext())
        .flatMapSingle(connectivity -> ReactiveNetwork.checkInternetConnectivity())
        .subscribeOn(Schedulers.io())
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(isConnected -> tvConnectivityStatus.setText(isConnected.toString()));
```

so basically I simplified this:

```java
        .flatMapSingle(connectivity -> {
          if (connectivity.getState() == NetworkInfo.State.CONNECTED) {
            return ReactiveNetwork.checkInternetConnectivity();
          }
          return Single.fromCallable(() -> false);
        })
```

to that:

```java
        .flatMapSingle(connectivity -> ReactiveNetwork.checkInternetConnectivity())
```

I've verified it with all 4 scenarios and it looks that it works fine now.

@vedantroy, please check if it solves your problem.

Nevertheless, I need to update docs in `README.md` to avoid such problems in the future.

**edit**: docs updated in  76ab2b2

**Comment by pwittchen** [comment]
I've got no response, so I assume problem no longer occurs.

Documentation is updated and with new code snippet, the application works properly and no false-positive results are returned.

All the details are provided in my posts above.

**Comment by vedantroy** [comment]
@pwittchen Sorry for not responding for a while! I've been busy. Unfortunately, the bug still remains. 

I can open my app while connected to both mobile and wifi. Then, after disconnecting from wifi, the status will remain disconnected, although I should have a mobile connection.

**Comment by pwittchen** [comment]
@vedantroy Have you tried **updated code snippet** I've posted here https://github.com/pwittchen/ReactiveNetwork/issues/276#issuecomment-396147241? With this update I cannot reproduce this bug. In the old snippet bug occurred as you wrote.
